### ISSUE TITLE
connections reset while creating many containers

### ISSUE THREAD

**Issue by giuseppe** [containers/netavark#210]
If I create containers in a loop like

```
# while true; do podman run --rm fedora true; done
```

the connections in the browser are resetted, tcpdump below:

```
15:48:52.735114 IP lithium.59138 > 52.142.124.215.https: Flags [R], seq 1236325112, win 0, length 0
15:48:52.735133 IP lithium.59138 > 52.142.124.215.https: Flags [R], seq 1236325112, win 0, length 0
15:48:52.753611 IP lithium.59138 > 52.142.124.215.https: Flags [R], seq 1236325113, win 0, length 0
15:48:55.956474 IP lithium.35234 > 104.244.42.2.https: Flags [R], seq 1116826531, win 0, length 0
15:48:55.956540 IP lithium.35234 > 104.244.42.2.https: Flags [R], seq 1116826531, win 0, length 0
15:48:55.957997 IP lithium.49848 > 104.244.42.1.https: Flags [R], seq 2014781109, win 0, length 0
15:48:55.958086 IP lithium.49848 > 104.244.42.1.https: Flags [R], seq 2014781109, win 0, length 0
15:48:55.958212 IP lithium.37044 > 104.244.42.69.https: Flags [R], seq 1558821107, win 0, length 0
15:48:55.958292 IP lithium.37044 > 104.244.42.69.https: Flags [R], seq 1558821107, win 0, length 0
15:48:57.379236 IP lithium.49850 > 104.244.42.1.https: Flags [R], seq 2559495239, win 0, length 0
```

I am using the latest git commit (34f1c0ae20a51339bbaaa94564bd65535defa229)

**Comment by Luap99** [comment]
Just to add some more information this happens on setup and teardown. I debugged the setup part and it happens when we set the container interface in the netns up.

**Comment by baude** [comment]
do we have any better idea of whats going on ?

**Comment by flouthoc** [comment]
I tried debugging this, the issue pops up as soon as we turn `hostend` of veth pair up. It does not matter if we do it inside the container namespace or outside both resets the connection.

Initially i thought its the issue in rust netlink bindings but after debugging i was unable to reproduce on a isolated rust netlink setup although my rust setup was different than netavark since it was missing other end of `veth` pair in a different network namespace.

I'll try with different kernel versions just to confirm but I doubt its a kernel issue as of now.

**Comment by baude** [comment]
would it warrant filing an upstream bug to see if you can extract any info/advice?

**Comment by flouthoc** [comment]
@baude I'll just try few bits more then file an issue cause i don't have flat `netlink rust` reproducer so it might be hard for `netlink` maintainers to read all netavark code and find if we are doing something wrong there. WDYT ?

**Comment by Luap99** [comment]
@flouthoc I tried it with an internal network without any firewall rules and it sill happens. So it is not related to firewall AFAICT

**Comment by flouthoc** [comment]
@Luap99 ackd. I'll try few more bits and update here as of now for me it does not resets all connections but few of them. @Luap99 What is happening in your reproducer ?

**Comment by flouthoc** [comment]
Just to add some info this only happens with `root`.

For me reset also happens with `CNI` but less frequently @Luap99 could you try the same experiment with latest podman and `CNI` on root and see if something similar happens for you or not ?

My reproducer is the same command which @giuseppe shared and i a monitoring with `tcpdump 'tcp[tcpflags] & tcp-rst != 0'`

Not sure about this at all: It could be something related to kernel not sure cause I see different behaviors in `5.14.16-201` and `5.15.10-200`.

**Comment by Luap99** [comment]
OK, I think I know what is causing this. I am able to reproduce this on the first container start with CNI.
The main difference between netavark and cni is that we remove the bridge on teardown when no other containers are using it.

So when we run with cni the bridge is not removed and therefore does not need to be created again for each container start.
Since netavark will create/remove the bridge for setup/teardown it will trigger a tcp reset.
I am unable to reproduce when we you have another container running in the background or you can use this patch to get cni behaviour with netavark: 
```diff
diff --git a/src/commands/teardown.rs b/src/commands/teardown.rs
index defa170..0170de0 100644
--- a/src/commands/teardown.rs
+++ b/src/commands/teardown.rs
@@ -176,7 +176,7 @@ impl Teardown {
                             }
                         }
                         // Teardown the interface now
-                        network::core_utils::CoreUtils::remove_interface(&interface_name)?;
+                        // network::core_utils::CoreUtils::remove_interface(&interface_name)?;
                     }
                 }
                 "macvlan" => {
```

**Comment by mheon** [comment]
It seems like it would be better to adopt CNI behavior, given this. Unfortunately, we'd need to shove the interface removal somewhere else for when we actually delete the network - maybe Podman, similar to how we handle deleting CNI networks?

**Comment by Luap99** [comment]
I don't think a tcp reset is a big problem IMO. This only happens if you restart a single container. As long as at least one container still runs we do not have this problem.

**Comment by Luap99** [comment]
Yes, lets close but please state you opinions on https://github.com/containers/podman/issues/17844 which would also address this issue here.
