### ISSUE TITLE
[Debian 11] Failed to Compile with `cargo-features = ["resolver"]`

### ISSUE THREAD

**Issue by hswong3i** [containers/netavark#250]
When packaging with Debian 11 .deb (https://github.com/alvistack/containers-netavark/commit/cb6a4437b78ae963d79d62f5d468eeb5c8064983 and https://build.opensuse.org/package/show/home:alvistack/containers-netavark-1.0.1), following error message happened:
```
[  123s] set -ex && \
[  123s] 	export VERGEN_GIT_SHA="5810f9fec619ddf3c95737f9ba26c67f43a6c88c" && \
[  123s] 	cargo build --release
[  123s] + export VERGEN_GIT_SHA=5810f9fec619ddf3c95737f9ba26c67f43a6c88c
[  123s] + VERGEN_GIT_SHA=5810f9fec619ddf3c95737f9ba26c67f43a6c88c
[  123s] + cargo build --release
[  123s] error: failed to get `anyhow` as a dependency of package `netavark v1.0.1 (/usr/src/packages/BUILD)`
[  123s] 
[  123s] Caused by:
[  123s]   failed to load source for dependency `anyhow`
[  123s] 
[  123s] Caused by:
[  123s]   Unable to update registry `https://github.com/rust-lang/crates.io-index`
[  123s] 
[  123s] Caused by:
[  123s]   failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`
[  123s] 
[  123s] Caused by:
[  123s]   failed to parse manifest at `/usr/src/packages/BUILD/vendor/zvariant/Cargo.toml`
[  123s] 
[  123s] Caused by:
[  123s]   feature `resolver` is required
[  123s] 
[  123s]   consider adding `cargo-features = ["resolver"]` to the manifest
```

This is most likely related to `zvariant/Cargo.toml` require `resolver = "2"` (see https://gitlab.freedesktop.org/dbus/zbus/-/blob/main/Cargo.toml#L3), which may not supported by Debian 11 Rust.

Steps for reproduce with podman:
```
$ sudo podman run -ti --rm --name debian-11 --hostname debian-11 debian:10
root@debian-11:~# apt update && apt -y full-upgrade
root@debian-11:~# apt -y install git cargo gcc
root@debian-11:~# git clone https://github.com/containers/netavark.git
root@debian-11:~# cd netavark/
root@debian-11:~/netavark# mkdir -p .cargo
root@debian-11:~/netavark# cargo vendor > .cargo/config.toml
    Updating crates.io index
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to download `zvariant_derive v3.1.2`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant_derive-3.1.2/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
  ```

**Comment by mheon** [comment]
We can't easily downgrade this dependency because of a recent major version bump in zbus/zvariant (there were breaking API changes due to a move to the use of async), so I don't think we can easily resolve this on our end.

**Comment by siretart** [comment]
It seems to me that you're asking netavark to compile with older versions of rust. @baude reached out to me about this issue and I'm happy to take a look.

to reproduce this with different versions of debian, I'm using this `Containerfile`:

```
FROM debian:10

RUN apt update && apt -y install git cargo gcc

RUN mkdir /build && cd /build && \
   git clone https://github.com/containers/netavark.git && \
   cd netavark/ && \
   mkdir -p .cargo && \
   cargo vendor > .cargo/config.toml && \
   cargo build
```

Note that I actually have 3 variations of this file that use different base images in line1:

* debian:10 (buster)
* debian:11 (bullseye)
* debian:sid (unstable)

Using "buster", a `podman build -f Containerfile` breaks with this error:

```
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/Cargo.toml`
```

Using "bullseye", a `podman build` returns this output:

```
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/iptables-0.5.0/Cargo.toml`
```

Using "sid", a `podman build` actually succeeds just fine.

Why is that? -- the reason is most likely the version of the rustc compiler supported by the different releases of debian:

| Debian Release | version |
|-|-|
| Debian 10 (buster)    | 1.41 |
| Debian 10 (bullseye) | 1.48 |
| Debian 10 (buster)    | 1.57 |

see https://tracker.debian.org/rustc for a more details.

I think it would be helpful if this project could clearly document what's the minimum required version of the rust compiler. It might also be useful to do a survey about the state of rust across different Linux distributions and architectures (luckily, at least in debian/bullseye, rustc has been successfully ported to every release architecture, including mips or s390x :-) )

**Comment by hswong3i** [comment]
Soled by manually dirty package Rust as https://build.opensuse.org/package/show/home:alvistack/rust-lang-rust-1.61.0 for my supported OS.
