### ISSUE TITLE
--ipam-driver=none and static ip assignments

### ISSUE THREAD

**Issue by nivekuil** [containers/netavark#301]
It looks like static IP assignments are completely ignored on a network with --ipam-driver=none, e.g. `podman run --net=podman4:ip=10.0.0.1 docker.io/bash ip a` has no IP assigned to that device. Is this intended? It would be helpful for this to work because the other options require a `--subnet` which causes podman to complain about an ip range conflict, when I want to manage the subnetting externally and just feed podman the static IP.

**Comment by Luap99** [comment]
Please provide more context, I am not sure what you are doing?

IPAM none means no ips. You network has no subnets in this case so it is impossible to assign ips. Just the ip from the run command cannot work since we need a subnet and gateway as well.

**Comment by Luap99** [comment]
> certainly this is not the case with iproute2 where you can ip a add whatever to a device

Well this is just wrong. If you omit the subnet you get a /32 subnet which is pointless since you cannot route any traffic with that. Thus your container will act like --net=none.

Networking always will require a subnet. This is just how it is designed. The gateway is required if you need to route traffic to external networks.

> I would also be happy if there were a way to skip the "subnet is already used on the host or by another config" check in podman network create.

This should not be removed. You will run into issues when you assigned the same subnet to two different interfaces.


It sound like you want the macvlan driver.

**Comment by Luap99** [comment]
Maybe I am mising something about ipv6 but I do not understand what the purpose of a /128 ip address is? This address is not routable. I think in your case everything goes over the link local address via NDP. So why assign the ip in the first place?

Regardless of this ipam none means no ips so we should not use them. I however think it should error out instead of ignoring it.

Have you looked into macvlan? I think this what you want.

**Comment by nivekuil** [comment]
Well a device on the link has to know which Neighbor Solicitations to respond (send out Neighbor Advertisements) to, and assigning the IP to a host interface seems to set up the host automatically to respond to those. We also need an ip to feed to `ip -6 neigh add proxy` so the host can proxy NDP on behalf of the pods. I don't think any real traffic goes over the link-local addresses, those are just used for protocol stuff, because I never bind anything to those and all is fine. 

As for macvlan it's orthogonal to my problem because you still need a `--subnet` to make a macvlan network, we still have to assign IPs within this subnet, and I'd like it to be the same /64 the host contains, so we still need the workaround of deleting the host's ip, creating the network, then re-adding it.

**Comment by nivekuil** [comment]
I'll close this issue because it seems I have misunderstood the intent of --ipam-driver=none. What I want might best be done by creating one network per pod.

**Comment by nivekuil** [comment]
ah yeah it does work. I think macvlan will probably not work well in shared hosting environments but if ipvlan l2 is ever added I will definitely try it.
