### ISSUE TITLE
Support request for user defined iptables or iptables off/false, as in Docker Engine

### ISSUE THREAD

**Issue by b1shan** [containers/netavark#339]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Unlike Docker Engine, Podman does not provide support for turning iptables off or false, such as in dockerd cli or config. Moreover, Podman does not provide a user chain, such as DOCKER-USER, where users can put their own rules with the guarantee that they won't be oven run by Docker Engine.

Ref:
https://docs.docker.com/network/iptables/

**Comment by mheon** [comment]
Transferring to Netavark

**Comment by fansari** [comment]
Is there any progress on this?

**Comment by Luap99** [comment]
no, contributions welcome, see https://github.com/containers/netavark/issues/339#issuecomment-1183282798 for a way to implement this

**Comment by oskarirauta** [comment]
I made a fork of netavark which completely disables all firewall features.

I first tried to make it possible to activate it through /etc/containers/networks/{network_name}.json but unfortunately it seems that firewall driver is decided before processing network configuration, so there is no chance to set firewall driver per network basis unless making larger changes. Second, I attempted to use NETAVARK_FW environment variable to be able to set "fwnone" firewall driver (forcibly set firewall driver) - but I did not find a way to do this, unless I make a shell script wrapper to netavark, so finally I just forced my fork to disable firewall. That worked out.

I then lefted as commented out, NETAVARK_FW handling code; in case this is useful for someone, and wish to use it through the mentioned wrapper.

Wrapper could be like this for example:
```
#!/bin/sh
/usr/bin/netavark-bin $@
```

https://github.com/oskarirauta/netavark/tree/fwnone

**Comment by Luap99** [comment]
@oskarirauta I think it makes sense to upstream the NETAVARK_FW option, we then can add a option to containers.conf to allow setting this value via config file and podman would just set this env when calling netavark.

Although I would prefer to call this option `none` instead of `fwnone`

**Comment by oskarirauta** [comment]
@Luap99 I was thinking exactly the same thing and can surely change it - even though I think this should be just a proof of concept and be re-done by maintainers, this was the first time I did anything in rust- so even though it works, I think experts might want to change some things..

I also sent a feature request to podman maintainers, since I did not found one before- for them to add support to such feature...

**Comment by oskarirauta** [comment]
@Luap99 I renamed it from fwnone to none

**Comment by fansari** [comment]
What I want is to have the same behaviour as this would do in docker:

/ec/docker/daemon.json

```
iptables: "false"
```

Which means that docker does not do any changes to his firewall rules.

The user then has to do everything he needs for docker on his own (e.g. defining masquerade rules for NAT).

I could not find a way to achieve this in podman except  for scrpting around in each and every container I control with systemd (see above). It would be much appreciated from my side if I finally could ge rid of this.

**Comment by oskarirauta** [comment]
Because there is no such feature implemented. Set a environment variable instead to disable firewalling features.Lähetetty iPhonestaFrank Ansari ***@***.***> kirjoitti 30.5.2023 kello 19.19:﻿
What I want is to have the same behaviour as this would do in docker:
/ec/docker/daemon.json
iptables: "false"

Which means that docker does not do any changes to his firewall rules.
The user then has to do everything he needs for docker on his own (e.g. defining masquerade rules for NAT).
I could not find a way to achieve this in podman except  for scrpting around in each and every container I control with systemd (see above). It would be much appreciated from my side if I finally could ge rid of this.

**Comment by beinbliss** [comment]
Another scenario. Podman is used for spawning hundreds of short lived containers, so it happens that hundreds of iptables rules are not cleaned when runtime crashes. Also it creates a separate masquerade rule for each container namespace in the same subnet, instead of just creating a single rule to masquerade internal ip subnet (like in docker case) thus saving lots of resources.

So having `"iptables": false` support would be great.

**Comment by Luap99** [comment]
The work here in netavark was done by @oskarirauta, you can set `NETAVARK_FW=none` to have that.

What is missing is a containers.conf option for that: https://github.com/containers/common/issues/1338.
But please refrain from making pointless comments there. If there are questions about how to implement it I am happy to answer.  If you just want this feature simply use the thumbs up function.
I see if I find some time in the future but in the meantime I welcome anybody to make a PR in c/common to add the new config field and pass it down to netavark.

Thus I am closing the issue here.

**Comment by fansari** [comment]
Finally it works for me.

I have put this into /etc/containers/containers.conf

```
[network]
network_backend = "netavark"
firewall_driver = "none"
```
Now netvark no longer tries to put its own rules into my nftables chain.

Tested with:
podman-5.0.1-1.fc40.x86_64
netavark-1.10.3-3.fc40.x86_64
